apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: namtx/kubia
          name: kubia
          ports:
            - containerPort: 8080
              protocol: TCP
