apiVersion: batch/v1
kind: Job
metadata:
  name: multiple-completions-job
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: multiple-completions-job
    spec:
      restartPolicy: OnFailure
      containers:
        - image: namtx/batch-job
          name: main
